FROM node:8.11.4-jessie as builder

ENV METEOR_ALLOW_SUPERUSER true

ENV APP_SCRIPTS_DIR /opt/meteor/scripts
ENV APP_SOURCE_DIR /opt/meteor/src
ENV APP_BUNDLE_DIR /opt/meteor/dist

COPY entrypoint-dev.sh $APP_SCRIPTS_DIR/

WORKDIR $APP_SOURCE_DIR

ENTRYPOINT $APP_SCRIPTS_DIR/entrypoint-dev.sh
