// flow-typed signature: 5fcc9ecd454d5ad0eb08362816df1757
// flow-typed version: <<STUB>>/apollo-boost_v^0.1.7/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-boost'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-boost' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-boost/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-boost/lib/index.js' {
  declare module.exports: $Exports<'apollo-boost/lib/index'>;
}
