// flow-typed signature: 105297464cdee29ceccb7e71206c32a2
// flow-typed version: <<STUB>>/apollo_v^1.9.2/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo/lib/commands/codegen/generate' {
  declare module.exports: any;
}

declare module 'apollo/lib/commands/queries/check' {
  declare module.exports: any;
}

declare module 'apollo/lib/commands/queries/extract' {
  declare module.exports: any;
}

declare module 'apollo/lib/commands/schema/check' {
  declare module.exports: any;
}

declare module 'apollo/lib/commands/schema/download' {
  declare module.exports: any;
}

declare module 'apollo/lib/commands/schema/publish' {
  declare module.exports: any;
}

declare module 'apollo/lib/config' {
  declare module.exports: any;
}

declare module 'apollo/lib/engine-cli' {
  declare module.exports: any;
}

declare module 'apollo/lib/engine' {
  declare module.exports: any;
}

declare module 'apollo/lib/fetch-schema' {
  declare module.exports: any;
}

declare module 'apollo/lib/generate' {
  declare module.exports: any;
}

declare module 'apollo/lib/git' {
  declare module.exports: any;
}

declare module 'apollo/lib/index' {
  declare module.exports: any;
}

declare module 'apollo/lib/load-config' {
  declare module.exports: any;
}

declare module 'apollo/lib/load-schema' {
  declare module.exports: any;
}

declare module 'apollo/lib/operations/schema' {
  declare module.exports: any;
}

declare module 'apollo/lib/operations/uploadSchema' {
  declare module.exports: any;
}

declare module 'apollo/lib/operations/validateOperations' {
  declare module.exports: any;
}

declare module 'apollo/lib/operations/validateSchema' {
  declare module.exports: any;
}

declare module 'apollo/lib/printer/ast' {
  declare module.exports: any;
}

declare module 'apollo/lib/printer/diff' {
  declare module.exports: any;
}

declare module 'apollo/lib/printer/emoji' {
  declare module.exports: any;
}

declare module 'apollo/lib/printer/print' {
  declare module.exports: any;
}

declare module 'apollo/lib/validation' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo/lib/commands/codegen/generate.js' {
  declare module.exports: $Exports<'apollo/lib/commands/codegen/generate'>;
}
declare module 'apollo/lib/commands/queries/check.js' {
  declare module.exports: $Exports<'apollo/lib/commands/queries/check'>;
}
declare module 'apollo/lib/commands/queries/extract.js' {
  declare module.exports: $Exports<'apollo/lib/commands/queries/extract'>;
}
declare module 'apollo/lib/commands/schema/check.js' {
  declare module.exports: $Exports<'apollo/lib/commands/schema/check'>;
}
declare module 'apollo/lib/commands/schema/download.js' {
  declare module.exports: $Exports<'apollo/lib/commands/schema/download'>;
}
declare module 'apollo/lib/commands/schema/publish.js' {
  declare module.exports: $Exports<'apollo/lib/commands/schema/publish'>;
}
declare module 'apollo/lib/config.js' {
  declare module.exports: $Exports<'apollo/lib/config'>;
}
declare module 'apollo/lib/engine-cli.js' {
  declare module.exports: $Exports<'apollo/lib/engine-cli'>;
}
declare module 'apollo/lib/engine.js' {
  declare module.exports: $Exports<'apollo/lib/engine'>;
}
declare module 'apollo/lib/fetch-schema.js' {
  declare module.exports: $Exports<'apollo/lib/fetch-schema'>;
}
declare module 'apollo/lib/generate.js' {
  declare module.exports: $Exports<'apollo/lib/generate'>;
}
declare module 'apollo/lib/git.js' {
  declare module.exports: $Exports<'apollo/lib/git'>;
}
declare module 'apollo/lib/index.js' {
  declare module.exports: $Exports<'apollo/lib/index'>;
}
declare module 'apollo/lib/load-config.js' {
  declare module.exports: $Exports<'apollo/lib/load-config'>;
}
declare module 'apollo/lib/load-schema.js' {
  declare module.exports: $Exports<'apollo/lib/load-schema'>;
}
declare module 'apollo/lib/operations/schema.js' {
  declare module.exports: $Exports<'apollo/lib/operations/schema'>;
}
declare module 'apollo/lib/operations/uploadSchema.js' {
  declare module.exports: $Exports<'apollo/lib/operations/uploadSchema'>;
}
declare module 'apollo/lib/operations/validateOperations.js' {
  declare module.exports: $Exports<'apollo/lib/operations/validateOperations'>;
}
declare module 'apollo/lib/operations/validateSchema.js' {
  declare module.exports: $Exports<'apollo/lib/operations/validateSchema'>;
}
declare module 'apollo/lib/printer/ast.js' {
  declare module.exports: $Exports<'apollo/lib/printer/ast'>;
}
declare module 'apollo/lib/printer/diff.js' {
  declare module.exports: $Exports<'apollo/lib/printer/diff'>;
}
declare module 'apollo/lib/printer/emoji.js' {
  declare module.exports: $Exports<'apollo/lib/printer/emoji'>;
}
declare module 'apollo/lib/printer/print.js' {
  declare module.exports: $Exports<'apollo/lib/printer/print'>;
}
declare module 'apollo/lib/validation.js' {
  declare module.exports: $Exports<'apollo/lib/validation'>;
}
