// flow-typed signature: 6addf270bed8997a567ee1de1bb61bd3
// flow-typed version: <<STUB>>/message-box_v^0.2.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'message-box'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'message-box' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'message-box/dist/MessageBox' {
  declare module.exports: any;
}

// Filename aliases
declare module 'message-box/dist/MessageBox.js' {
  declare module.exports: $Exports<'message-box/dist/MessageBox'>;
}
