// flow-typed signature: 858057cd3dab90f120f92961684a7410
// flow-typed version: <<STUB>>/react-star-rating-component_v^1.3.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-star-rating-component'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-star-rating-component' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-star-rating-component/dist/react-star-rating-component' {
  declare module.exports: any;
}

declare module 'react-star-rating-component/dist/react-star-rating-component.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-star-rating-component/dist/react-star-rating-component.js' {
  declare module.exports: $Exports<'react-star-rating-component/dist/react-star-rating-component'>;
}
declare module 'react-star-rating-component/dist/react-star-rating-component.min.js' {
  declare module.exports: $Exports<'react-star-rating-component/dist/react-star-rating-component.min'>;
}
declare module 'react-star-rating-component/index' {
  declare module.exports: $Exports<'react-star-rating-component'>;
}
declare module 'react-star-rating-component/index.js' {
  declare module.exports: $Exports<'react-star-rating-component'>;
}
