// flow-typed signature: e3a450c3090b887b95c4c18f0a98b140
// flow-typed version: <<STUB>>/react-star-ratings_v^2.2.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-star-ratings'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-star-ratings' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-star-ratings/build/index' {
  declare module.exports: any;
}

declare module 'react-star-ratings/build/star-ratings' {
  declare module.exports: any;
}

declare module 'react-star-ratings/build/star' {
  declare module.exports: any;
}

declare module 'react-star-ratings/src/index' {
  declare module.exports: any;
}

declare module 'react-star-ratings/src/star-ratings' {
  declare module.exports: any;
}

declare module 'react-star-ratings/src/star' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-star-ratings/build/index.js' {
  declare module.exports: $Exports<'react-star-ratings/build/index'>;
}
declare module 'react-star-ratings/build/star-ratings.js' {
  declare module.exports: $Exports<'react-star-ratings/build/star-ratings'>;
}
declare module 'react-star-ratings/build/star.js' {
  declare module.exports: $Exports<'react-star-ratings/build/star'>;
}
declare module 'react-star-ratings/index' {
  declare module.exports: $Exports<'react-star-ratings'>;
}
declare module 'react-star-ratings/index.js' {
  declare module.exports: $Exports<'react-star-ratings'>;
}
declare module 'react-star-ratings/src/index.js' {
  declare module.exports: $Exports<'react-star-ratings/src/index'>;
}
declare module 'react-star-ratings/src/star-ratings.js' {
  declare module.exports: $Exports<'react-star-ratings/src/star-ratings'>;
}
declare module 'react-star-ratings/src/star.js' {
  declare module.exports: $Exports<'react-star-ratings/src/star'>;
}
