// flow-typed signature: f002afa3835f0214a4b50fc95a012336
// flow-typed version: <<STUB>>/react-simple-dropdown_v^3.2.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-simple-dropdown'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-simple-dropdown' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-simple-dropdown/docs/index' {
  declare module.exports: any;
}

declare module 'react-simple-dropdown/lib/components/Dropdown' {
  declare module.exports: any;
}

declare module 'react-simple-dropdown/lib/components/DropdownContent' {
  declare module.exports: any;
}

declare module 'react-simple-dropdown/lib/components/DropdownTrigger' {
  declare module.exports: any;
}

declare module 'react-simple-dropdown/src/components/Dropdown' {
  declare module.exports: any;
}

declare module 'react-simple-dropdown/src/components/DropdownContent' {
  declare module.exports: any;
}

declare module 'react-simple-dropdown/src/components/DropdownTrigger' {
  declare module.exports: any;
}

declare module 'react-simple-dropdown/src/docs/components/AccountDropdown' {
  declare module.exports: any;
}

declare module 'react-simple-dropdown/src/docs/index' {
  declare module.exports: any;
}

declare module 'react-simple-dropdown/test/components/Dropdown' {
  declare module.exports: any;
}

declare module 'react-simple-dropdown/test/components/DropdownContent' {
  declare module.exports: any;
}

declare module 'react-simple-dropdown/test/components/DropdownTrigger' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-simple-dropdown/docs/index.js' {
  declare module.exports: $Exports<'react-simple-dropdown/docs/index'>;
}
declare module 'react-simple-dropdown/lib/components/Dropdown.js' {
  declare module.exports: $Exports<'react-simple-dropdown/lib/components/Dropdown'>;
}
declare module 'react-simple-dropdown/lib/components/DropdownContent.js' {
  declare module.exports: $Exports<'react-simple-dropdown/lib/components/DropdownContent'>;
}
declare module 'react-simple-dropdown/lib/components/DropdownTrigger.js' {
  declare module.exports: $Exports<'react-simple-dropdown/lib/components/DropdownTrigger'>;
}
declare module 'react-simple-dropdown/src/components/Dropdown.jsx' {
  declare module.exports: $Exports<'react-simple-dropdown/src/components/Dropdown'>;
}
declare module 'react-simple-dropdown/src/components/DropdownContent.jsx' {
  declare module.exports: $Exports<'react-simple-dropdown/src/components/DropdownContent'>;
}
declare module 'react-simple-dropdown/src/components/DropdownTrigger.jsx' {
  declare module.exports: $Exports<'react-simple-dropdown/src/components/DropdownTrigger'>;
}
declare module 'react-simple-dropdown/src/docs/components/AccountDropdown.jsx' {
  declare module.exports: $Exports<'react-simple-dropdown/src/docs/components/AccountDropdown'>;
}
declare module 'react-simple-dropdown/src/docs/index.jsx' {
  declare module.exports: $Exports<'react-simple-dropdown/src/docs/index'>;
}
declare module 'react-simple-dropdown/test/components/Dropdown.jsx' {
  declare module.exports: $Exports<'react-simple-dropdown/test/components/Dropdown'>;
}
declare module 'react-simple-dropdown/test/components/DropdownContent.jsx' {
  declare module.exports: $Exports<'react-simple-dropdown/test/components/DropdownContent'>;
}
declare module 'react-simple-dropdown/test/components/DropdownTrigger.jsx' {
  declare module.exports: $Exports<'react-simple-dropdown/test/components/DropdownTrigger'>;
}
