drop view comment_vote_counts;
drop view comments_with_vote_counts;
drop view company_review_statistics;
drop view company_salary_income_amount;
drop view company_salary_statistics;
drop view job_post_counts;
drop view review_vote_counts;
drop view reviews_with_vote_counts;
drop view salary_counts;
