#!/bin/bash

case $1 in
"mongo-start")
	sudo docker run \
		--name mongo \
		-v mongo-data:/data/db \
		-p 27017:27017 \
		--rm -d mongo:3.4
	;;
"meteor")
	MONGO_URL='mongodb://localhost:27017/meteor' meteor
	;;
"mongo-stop")
	sudo docker kill mongo
	;;
*)
	echo "Unknown command $1"
	exit 1
	;;
esac
